# Generated by Django 5.2.16 on 2026-08-04 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=40)),
                ("grade", models.CharField(max_length=40)),
                ("topic", models.CharField(max_length=200)),
                ("class_hours", models.PositiveSmallIntegerField(default=1)),
                ("student_context", models.TextField(blank=True, default="")),
                ("requirements", models.TextField(blank=True, default="")),
                ("generated_content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subject", models.CharField(blank=True, default="", max_length=40)),
                ("grade", models.CharField(blank=True, default="", max_length=40)),
                (
                    "course_teacher",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "media_file",
                    models.FileField(
                        blank=True, null=True, upload_to="lesson_reviews/%Y/%m/"
                    ),
                ),
                ("transcript", models.TextField(blank=True, default="")),
                ("report_content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("raw_text", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("reflection", "教学反思"),
                            ("learning", "学习心得"),
                            ("lesson_review", "听评课"),
                            ("collective", "集体备课"),
                            ("idea", "教学灵感"),
                        ],
                        default="reflection",
                        max_length=30,
                    ),
                ),
                (
                    "input_method",
                    models.CharField(
                        choices=[
                            ("text", "手动输入"),
                            ("voice", "语音录入"),
                            ("file", "文件上传"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=40)),
                ("grade", models.CharField(blank=True, default="", max_length=40)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "source_file",
                    models.FileField(
                        blank=True, null=True, upload_to="notes/files/%Y/%m/"
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="notes/audio/%Y/%m/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("weekly", "教学周报"),
                            ("monthly", "教学月报"),
                            ("semester", "学期教研总结"),
                            ("growth", "个人成长报告"),
                            ("topic", "专题教学分析"),
                        ],
                        default="weekly",
                        max_length=30,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_notes",
                    models.ManyToManyField(
                        related_name="generated_reports", to="learning.researchnote"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
