# Generated by Django 5.2.16 on 2026-09-01 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessonplan",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "教学设计",
                "verbose_name_plural": "教学设计",
            },
        ),
        migrations.AlterModelOptions(
            name="lessonreview",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "听评课记录",
                "verbose_name_plural": "听评课记录",
            },
        ),
        migrations.AlterModelOptions(
            name="researchnote",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "教研笔记",
                "verbose_name_plural": "教研笔记",
            },
        ),
        migrations.AlterModelOptions(
            name="researchreport",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "教研报告",
                "verbose_name_plural": "教研报告",
            },
        ),
        migrations.AlterField(
            model_name="lessonplan",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
        migrations.AlterField(
            model_name="lessonplan",
            name="class_hours",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="课时"),
        ),
        migrations.AlterField(
            model_name="lessonplan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="lessonplan",
            name="generated_content",
            field=models.TextField(verbose_name="生成内容"),
        ),
        migrations.AlterField(
            model_name="lessonplan",
            name="grade",
            field=models.CharField(max_length=40, verbose_name="年级"),
        ),
        migrations.AlterField(
            model_name="lessonplan",
            name="requirements",
            field=models.TextField(blank=True, default="", verbose_name="要求"),
        ),
        migrations.AlterField(
            model_name="lessonplan",
            name="student_context",
            field=models.TextField(blank=True, default="", verbose_name="学情"),
        ),
        migrations.AlterField(
            model_name="lessonplan",
            name="subject",
            field=models.CharField(max_length=40, verbose_name="学科"),
        ),
        migrations.AlterField(
            model_name="lessonplan",
            name="title",
            field=models.CharField(max_length=200, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="lessonplan",
            name="topic",
            field=models.CharField(max_length=200, verbose_name="课题"),
        ),
        migrations.AlterField(
            model_name="lessonreview",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
        migrations.AlterField(
            model_name="lessonreview",
            name="course_teacher",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="授课教师"
            ),
        ),
        migrations.AlterField(
            model_name="lessonreview",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="lessonreview",
            name="grade",
            field=models.CharField(
                blank=True, default="", max_length=40, verbose_name="年级"
            ),
        ),
        migrations.AlterField(
            model_name="lessonreview",
            name="media_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="lesson_reviews/%Y/%m/",
                verbose_name="音视频",
            ),
        ),
        migrations.AlterField(
            model_name="lessonreview",
            name="report_content",
            field=models.TextField(verbose_name="评课报告"),
        ),
        migrations.AlterField(
            model_name="lessonreview",
            name="subject",
            field=models.CharField(
                blank=True, default="", max_length=40, verbose_name="学科"
            ),
        ),
        migrations.AlterField(
            model_name="lessonreview",
            name="title",
            field=models.CharField(max_length=200, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="lessonreview",
            name="transcript",
            field=models.TextField(blank=True, default="", verbose_name="转写文本"),
        ),
        migrations.AlterField(
            model_name="researchnote",
            name="audio_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="notes/audio/%Y/%m/",
                verbose_name="音频",
            ),
        ),
        migrations.AlterField(
            model_name="researchnote",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="research_notes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
        migrations.AlterField(
            model_name="researchnote",
            name="category",
            field=models.CharField(
                choices=[
                    ("reflection", "教学反思"),
                    ("learning", "学习心得"),
                    ("lesson_review", "听评课"),
                    ("collective", "集体备课"),
                    ("idea", "教学灵感"),
                ],
                default="reflection",
                max_length=30,
                verbose_name="分类",
            ),
        ),
        migrations.AlterField(
            model_name="researchnote",
            name="content",
            field=models.TextField(verbose_name="内容"),
        ),
        migrations.AlterField(
            model_name="researchnote",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="researchnote",
            name="grade",
            field=models.CharField(
                blank=True, default="", max_length=40, verbose_name="年级"
            ),
        ),
        migrations.AlterField(
            model_name="researchnote",
            name="input_method",
            field=models.CharField(
                choices=[
                    ("text", "手动输入"),
                    ("voice", "语音录入"),
                    ("file", "文件上传"),
                ],
                default="text",
                max_length=20,
                verbose_name="录入方式",
            ),
        ),
        migrations.AlterField(
            model_name="researchnote",
            name="raw_text",
            field=models.TextField(blank=True, default="", verbose_name="原始文本"),
        ),
        migrations.AlterField(
            model_name="researchnote",
            name="source_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="notes/files/%Y/%m/",
                verbose_name="附件",
            ),
        ),
        migrations.AlterField(
            model_name="researchnote",
            name="subject",
            field=models.CharField(
                blank=True, default="", max_length=40, verbose_name="学科"
            ),
        ),
        migrations.AlterField(
            model_name="researchnote",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="标签"),
        ),
        migrations.AlterField(
            model_name="researchnote",
            name="title",
            field=models.CharField(max_length=200, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="researchnote",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="researchreport",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="research_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
        migrations.AlterField(
            model_name="researchreport",
            name="content",
            field=models.TextField(verbose_name="内容"),
        ),
        migrations.AlterField(
            model_name="researchreport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="researchreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("weekly", "教学周报"),
                    ("monthly", "教学月报"),
                    ("semester", "学期教研总结"),
                    ("growth", "个人成长报告"),
                    ("topic", "专题教学分析"),
                ],
                default="weekly",
                max_length=30,
                verbose_name="报告类型",
            ),
        ),
        migrations.AlterField(
            model_name="researchreport",
            name="source_notes",
            field=models.ManyToManyField(
                related_name="generated_reports",
                to="learning.researchnote",
                verbose_name="来源笔记",
            ),
        ),
        migrations.AlterField(
            model_name="researchreport",
            name="title",
            field=models.CharField(max_length=200, verbose_name="标题"),
        ),
        migrations.CreateModel(
            name="AssistantChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="新对话", max_length=80, verbose_name="标题"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_chats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
            ],
            options={
                "verbose_name": "智能体对话",
                "verbose_name_plural": "智能体对话",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AssistantMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "教师"), ("assistant", "助手")],
                        max_length=16,
                        verbose_name="角色",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="learning.assistantchat",
                        verbose_name="对话",
                    ),
                ),
            ],
            options={
                "verbose_name": "智能体消息",
                "verbose_name_plural": "智能体消息",
                "ordering": ["created_at"],
            },
        ),
    ]
